version: '3'

networks:
  es_cluster:
    driver: bridge

services:
  elasticsearch01:
    image: ashokkumarchoppadandi/elasticsearch:latest 
    hostname: eshost1
    networks:
      - es_cluster
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      HOSTNAME: eshost1
      ES_CLUSTER_NAME: my-elasticsearch
      ES_NODE_NAME: eshost1
      ES_NODE_MASTER: "true"
      ES_DATA_PATH: "/usr/local/elasticsearch/data/"
      ES_LOGS_PATH: "/usr/local/elasticsearch/logs/"
      ES_NETWORK_HOST: 0.0.0.0
      ES_HTTP_PORT: 9200
      ES_BOOTSTRAP_MEMORY_LOCK: "true"
      ES_DISCOVERY_SEED_HOSTS: "127.0.0.1, [::1]"
      ES_MASTER_NODES: eshost1
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1

